name: rueo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_html: ^0.11.1
  shared_preferences: ^2.0.15
  enum_to_string: ^2.0.1
  elementary: ^1.1.3
  get_it: ^7.2.0
  flutter_svg: ^1.1.1+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/esperanto_star.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

